// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace CsBindgen
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "csbindings";



        [DllImport(__DllName, EntryPoint = "is_manifest_null", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool is_manifest_null();

        /// <summary># Safety No</summary>
        [DllImport(__DllName, EntryPoint = "get_version_manifest", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaskWrapper* get_version_manifest();

        /// <summary># Safety No</summary>
        [DllImport(__DllName, EntryPoint = "poll_manifest_task", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        public static extern bool poll_manifest_task(TaskWrapper* task);

        /// <summary>This function consumes the task wrapper, dropping it, setting the manifest wrapper to a proper value And then return a NativeReturn, specifying if it's a success or error This is used to tell if this should be converted a C# exception  # Safety # The task wrapper cannot be Null # The manifest wrapper cannot be null</summary>
        [DllImport(__DllName, EntryPoint = "get_manifest", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern NativeReturn get_manifest(TaskWrapper* task);

        /// <summary># Safety # Manifest Wrapper cannot equal null</summary>
        [DllImport(__DllName, EntryPoint = "get_latest_release", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern RefStringWrapper get_latest_release();

        /// <summary># Safety # Manifest Wrapper cannot equal Null</summary>
        [DllImport(__DllName, EntryPoint = "get_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern RefStringWrapper get_name(nuint index);

        /// <summary># Safety</summary>
        [DllImport(__DllName, EntryPoint = "get_manifest_len", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern nuint get_manifest_len();

        /// <summary># Safety The manifest wrapper cannot be null</summary>
        [DllImport(__DllName, EntryPoint = "get_type", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ReleaseType get_type(nuint index);

        [DllImport(__DllName, EntryPoint = "free_string_wrapper", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void free_string_wrapper(OwnedStringWrapper string_wrapper);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct NativeReturn
    {
        public Code code;
        public OwnedStringWrapper error;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TaskWrapper
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct RefStringWrapper
    {
        public byte* char_ptr;
        public nuint len;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct OwnedStringWrapper
    {
        public byte* char_ptr;
        public nuint len;
    }


    internal enum Code : uint
    {
        Success,
        RequestError,
        IOError,
        SerdeError,
    }

    internal enum ReleaseType : uint
    {
        OldAlpha,
        OldBeta,
        Release,
        Snapshot,
    }


}
    